#handler --> All Done
helpers --> pep.py(all), lets(X), lets(exceptions class 중복 3개 있음)
loginEvent.py/loginFailedException_pep로 고쳐놓음
#objects --> All Done
pubSubHandlers --> pep.py(X), lets(X)